config/routes.rb
Rails.application.routes.draw do
  root 'foot_traffics#new'
  resources :foot_traffics, only: %i[show new create]
end

app/models/application_record.rb
# All models have the parent as ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foot_traffic.rb
# model for the gallery's foot traffic analysis
class FootTraffic < ApplicationRecord
  mount_uploader :log, LogUploader

  def traffic_analysis(log_url)
    traffic_analysis = FootTrafficAnalysis.new(LogFile.new(log_url))
    traffic_analysis.print_report
  end

  def generate_traffic_report(foot_traffic, log)
    foot_traffic.log = log
    foot_traffic.save
    traffic_analysis(foot_traffic.log.current_path)
  end
end

app/controllers/application_controller.rb
# application level controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foot_traffics_controller.rb
# controller for generating foot  traffic report
class FootTrafficsController < ApplicationController
  before_action :set_foot_traffic, only: [:show]

  def show; end

  def new
    @foot_traffic = FootTraffic.new
  end

  def create
    @foot_traffic = FootTraffic.new
    report = @foot_traffic.generate_traffic_report(@foot_traffic,
                                                   foot_traffic_params[:log])
    report_text = "Foot Traffic Analysis Report: #{report}"
    if report.present?
      redirect_to @foot_traffic, notice: report_text
    else
      format.html { render :new }
    end
  end

  private

  def set_foot_traffic
    @foot_traffic = FootTraffic.find(params[:id])
  end

  def foot_traffic_params
    params.require(:foot_traffic)
          .permit(:room_id, :average_visit, :num_of_visitors, :log)
  end
end

app/helpers/application_helper.rb
# module for  the application level helpers
module ApplicationHelper
end

app/views/foot_traffics/_form.html.erb
<%= form_for(foot_traffic) do |f| %>
  <% if foot_traffic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foot_traffic.errors.count, "error") %> prohibited this foot_traffic from being saved:</h2>

      <ul>
      <% foot_traffic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :log %>
  </div>

  <div class="actions">
    <%= f.submit 'Generate Gallery Traffic Report' %>
  </div>
<% end %>

app/views/foot_traffics/new.html.erb
<h1>Please Upload the art gallery visits file in .txt format</h1>

<%= render 'form', foot_traffic: @foot_traffic %>

<%= link_to 'Back', foot_traffics_path %>

app/views/foot_traffics/show.html.erb
<p>
  <strong>Gallery Traffic Report:</strong>
  <%= @foot_traffic.room_id %>
</p>

<p id="notice"><%= notice %></p>

<%= link_to 'Back', new_foot_traffic_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtGallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
		body {
			background-color: lightblue;
		}
  </style>

  <body>
    <%= yield %>
  </body>
</html>